language: node_js
node_js:
- node
script:
- npm run lint
- npm run test
- npm run build
deploy:
  provider: pages
  script: deploy
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  name: $GITHUB_USERNAME
  email: $GITHUB_EMAIL
  target_branch: master
  on:
    branch: src
    tags: true
